// import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

const geistMono = Geist_Mono({
    subsets: ["latin"],
    variable: "--font-geist-mono",
    display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${geistMono.variable} antialiased font-sans m-4`}
            >
                <header>
                    <section className="bg-MotiMateLogo  bg-no-repeat bg-center bg-contain p-1 py-10">
                        <h1 className="text-9xl font-extrabold text-center bg-opacity-70 bg-white">
                            MotiMate
                        </h1>
                    </section>
                </header>

                {children}
            </body>
        </html>
    );
}
